// Code generated by protoc-gen-go.
// source: riak.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RpbIndexReq_IndexQueryType int32

const (
	RpbIndexReq_eq    RpbIndexReq_IndexQueryType = 0
	RpbIndexReq_range RpbIndexReq_IndexQueryType = 1
)

var RpbIndexReq_IndexQueryType_name = map[int32]string{
	0: "eq",
	1: "range",
}
var RpbIndexReq_IndexQueryType_value = map[string]int32{
	"eq":    0,
	"range": 1,
}

func (x RpbIndexReq_IndexQueryType) Enum() *RpbIndexReq_IndexQueryType {
	p := new(RpbIndexReq_IndexQueryType)
	*p = x
	return p
}
func (x RpbIndexReq_IndexQueryType) String() string {
	return proto.EnumName(RpbIndexReq_IndexQueryType_name, int32(x))
}
func (x RpbIndexReq_IndexQueryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RpbIndexReq_IndexQueryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpbIndexReq_IndexQueryType_value, data, "RpbIndexReq_IndexQueryType")
	if err != nil {
		return err
	}
	*x = RpbIndexReq_IndexQueryType(value)
	return nil
}

type RpbErrorResp struct {
	Errmsg           []byte  `protobuf:"bytes,1,req,name=errmsg" json:"errmsg,omitempty"`
	Errcode          *uint32 `protobuf:"varint,2,req,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbErrorResp) Reset()         { *this = RpbErrorResp{} }
func (this *RpbErrorResp) String() string { return proto.CompactTextString(this) }
func (*RpbErrorResp) ProtoMessage()       {}

func (this *RpbErrorResp) GetErrmsg() []byte {
	if this != nil {
		return this.Errmsg
	}
	return nil
}

func (this *RpbErrorResp) GetErrcode() uint32 {
	if this != nil && this.Errcode != nil {
		return *this.Errcode
	}
	return 0
}

type RpbGetServerInfoResp struct {
	Node             []byte `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	ServerVersion    []byte `protobuf:"bytes,2,opt,name=server_version" json:"server_version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbGetServerInfoResp) Reset()         { *this = RpbGetServerInfoResp{} }
func (this *RpbGetServerInfoResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetServerInfoResp) ProtoMessage()       {}

func (this *RpbGetServerInfoResp) GetNode() []byte {
	if this != nil {
		return this.Node
	}
	return nil
}

func (this *RpbGetServerInfoResp) GetServerVersion() []byte {
	if this != nil {
		return this.ServerVersion
	}
	return nil
}

type RpbPair struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbPair) Reset()         { *this = RpbPair{} }
func (this *RpbPair) String() string { return proto.CompactTextString(this) }
func (*RpbPair) ProtoMessage()       {}

func (this *RpbPair) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbPair) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type RpbGetClientIdResp struct {
	ClientId         []byte `protobuf:"bytes,1,req,name=client_id" json:"client_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbGetClientIdResp) Reset()         { *this = RpbGetClientIdResp{} }
func (this *RpbGetClientIdResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetClientIdResp) ProtoMessage()       {}

func (this *RpbGetClientIdResp) GetClientId() []byte {
	if this != nil {
		return this.ClientId
	}
	return nil
}

type RpbSetClientIdReq struct {
	ClientId         []byte `protobuf:"bytes,1,req,name=client_id" json:"client_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbSetClientIdReq) Reset()         { *this = RpbSetClientIdReq{} }
func (this *RpbSetClientIdReq) String() string { return proto.CompactTextString(this) }
func (*RpbSetClientIdReq) ProtoMessage()       {}

func (this *RpbSetClientIdReq) GetClientId() []byte {
	if this != nil {
		return this.ClientId
	}
	return nil
}

type RpbGetReq struct {
	Bucket           []byte  `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Key              []byte  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	R                *uint32 `protobuf:"varint,3,opt,name=r" json:"r,omitempty"`
	Pr               *uint32 `protobuf:"varint,4,opt,name=pr" json:"pr,omitempty"`
	BasicQuorum      *bool   `protobuf:"varint,5,opt,name=basic_quorum" json:"basic_quorum,omitempty"`
	NotfoundOk       *bool   `protobuf:"varint,6,opt,name=notfound_ok" json:"notfound_ok,omitempty"`
	IfModified       []byte  `protobuf:"bytes,7,opt,name=if_modified" json:"if_modified,omitempty"`
	Head             *bool   `protobuf:"varint,8,opt,name=head" json:"head,omitempty"`
	Deletedvclock    *bool   `protobuf:"varint,9,opt,name=deletedvclock" json:"deletedvclock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbGetReq) Reset()         { *this = RpbGetReq{} }
func (this *RpbGetReq) String() string { return proto.CompactTextString(this) }
func (*RpbGetReq) ProtoMessage()       {}

func (this *RpbGetReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbGetReq) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbGetReq) GetR() uint32 {
	if this != nil && this.R != nil {
		return *this.R
	}
	return 0
}

func (this *RpbGetReq) GetPr() uint32 {
	if this != nil && this.Pr != nil {
		return *this.Pr
	}
	return 0
}

func (this *RpbGetReq) GetBasicQuorum() bool {
	if this != nil && this.BasicQuorum != nil {
		return *this.BasicQuorum
	}
	return false
}

func (this *RpbGetReq) GetNotfoundOk() bool {
	if this != nil && this.NotfoundOk != nil {
		return *this.NotfoundOk
	}
	return false
}

func (this *RpbGetReq) GetIfModified() []byte {
	if this != nil {
		return this.IfModified
	}
	return nil
}

func (this *RpbGetReq) GetHead() bool {
	if this != nil && this.Head != nil {
		return *this.Head
	}
	return false
}

func (this *RpbGetReq) GetDeletedvclock() bool {
	if this != nil && this.Deletedvclock != nil {
		return *this.Deletedvclock
	}
	return false
}

type RpbGetResp struct {
	Content          []*RpbContent `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
	Vclock           []byte        `protobuf:"bytes,2,opt,name=vclock" json:"vclock,omitempty"`
	Unchanged        *bool         `protobuf:"varint,3,opt,name=unchanged" json:"unchanged,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *RpbGetResp) Reset()         { *this = RpbGetResp{} }
func (this *RpbGetResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetResp) ProtoMessage()       {}

func (this *RpbGetResp) GetVclock() []byte {
	if this != nil {
		return this.Vclock
	}
	return nil
}

func (this *RpbGetResp) GetUnchanged() bool {
	if this != nil && this.Unchanged != nil {
		return *this.Unchanged
	}
	return false
}

type RpbPutReq struct {
	Bucket           []byte      `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Key              []byte      `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Vclock           []byte      `protobuf:"bytes,3,opt,name=vclock" json:"vclock,omitempty"`
	Content          *RpbContent `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	W                *uint32     `protobuf:"varint,5,opt,name=w" json:"w,omitempty"`
	Dw               *uint32     `protobuf:"varint,6,opt,name=dw" json:"dw,omitempty"`
	ReturnBody       *bool       `protobuf:"varint,7,opt,name=return_body" json:"return_body,omitempty"`
	Pw               *uint32     `protobuf:"varint,8,opt,name=pw" json:"pw,omitempty"`
	IfNotModified    *bool       `protobuf:"varint,9,opt,name=if_not_modified" json:"if_not_modified,omitempty"`
	IfNoneMatch      *bool       `protobuf:"varint,10,opt,name=if_none_match" json:"if_none_match,omitempty"`
	ReturnHead       *bool       `protobuf:"varint,11,opt,name=return_head" json:"return_head,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (this *RpbPutReq) Reset()         { *this = RpbPutReq{} }
func (this *RpbPutReq) String() string { return proto.CompactTextString(this) }
func (*RpbPutReq) ProtoMessage()       {}

func (this *RpbPutReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbPutReq) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbPutReq) GetVclock() []byte {
	if this != nil {
		return this.Vclock
	}
	return nil
}

func (this *RpbPutReq) GetContent() *RpbContent {
	if this != nil {
		return this.Content
	}
	return nil
}

func (this *RpbPutReq) GetW() uint32 {
	if this != nil && this.W != nil {
		return *this.W
	}
	return 0
}

func (this *RpbPutReq) GetDw() uint32 {
	if this != nil && this.Dw != nil {
		return *this.Dw
	}
	return 0
}

func (this *RpbPutReq) GetReturnBody() bool {
	if this != nil && this.ReturnBody != nil {
		return *this.ReturnBody
	}
	return false
}

func (this *RpbPutReq) GetPw() uint32 {
	if this != nil && this.Pw != nil {
		return *this.Pw
	}
	return 0
}

func (this *RpbPutReq) GetIfNotModified() bool {
	if this != nil && this.IfNotModified != nil {
		return *this.IfNotModified
	}
	return false
}

func (this *RpbPutReq) GetIfNoneMatch() bool {
	if this != nil && this.IfNoneMatch != nil {
		return *this.IfNoneMatch
	}
	return false
}

func (this *RpbPutReq) GetReturnHead() bool {
	if this != nil && this.ReturnHead != nil {
		return *this.ReturnHead
	}
	return false
}

type RpbPutResp struct {
	Content          []*RpbContent `protobuf:"bytes,1,rep,name=content" json:"content,omitempty"`
	Vclock           []byte        `protobuf:"bytes,2,opt,name=vclock" json:"vclock,omitempty"`
	Key              []byte        `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (this *RpbPutResp) Reset()         { *this = RpbPutResp{} }
func (this *RpbPutResp) String() string { return proto.CompactTextString(this) }
func (*RpbPutResp) ProtoMessage()       {}

func (this *RpbPutResp) GetVclock() []byte {
	if this != nil {
		return this.Vclock
	}
	return nil
}

func (this *RpbPutResp) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

type RpbDelReq struct {
	Bucket           []byte  `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Key              []byte  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Rw               *uint32 `protobuf:"varint,3,opt,name=rw" json:"rw,omitempty"`
	Vclock           []byte  `protobuf:"bytes,4,opt,name=vclock" json:"vclock,omitempty"`
	R                *uint32 `protobuf:"varint,5,opt,name=r" json:"r,omitempty"`
	W                *uint32 `protobuf:"varint,6,opt,name=w" json:"w,omitempty"`
	Pr               *uint32 `protobuf:"varint,7,opt,name=pr" json:"pr,omitempty"`
	Pw               *uint32 `protobuf:"varint,8,opt,name=pw" json:"pw,omitempty"`
	Dw               *uint32 `protobuf:"varint,9,opt,name=dw" json:"dw,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbDelReq) Reset()         { *this = RpbDelReq{} }
func (this *RpbDelReq) String() string { return proto.CompactTextString(this) }
func (*RpbDelReq) ProtoMessage()       {}

func (this *RpbDelReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbDelReq) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbDelReq) GetRw() uint32 {
	if this != nil && this.Rw != nil {
		return *this.Rw
	}
	return 0
}

func (this *RpbDelReq) GetVclock() []byte {
	if this != nil {
		return this.Vclock
	}
	return nil
}

func (this *RpbDelReq) GetR() uint32 {
	if this != nil && this.R != nil {
		return *this.R
	}
	return 0
}

func (this *RpbDelReq) GetW() uint32 {
	if this != nil && this.W != nil {
		return *this.W
	}
	return 0
}

func (this *RpbDelReq) GetPr() uint32 {
	if this != nil && this.Pr != nil {
		return *this.Pr
	}
	return 0
}

func (this *RpbDelReq) GetPw() uint32 {
	if this != nil && this.Pw != nil {
		return *this.Pw
	}
	return 0
}

func (this *RpbDelReq) GetDw() uint32 {
	if this != nil && this.Dw != nil {
		return *this.Dw
	}
	return 0
}

type RpbListBucketsResp struct {
	Buckets          [][]byte `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *RpbListBucketsResp) Reset()         { *this = RpbListBucketsResp{} }
func (this *RpbListBucketsResp) String() string { return proto.CompactTextString(this) }
func (*RpbListBucketsResp) ProtoMessage()       {}

type RpbListKeysReq struct {
	Bucket           []byte `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbListKeysReq) Reset()         { *this = RpbListKeysReq{} }
func (this *RpbListKeysReq) String() string { return proto.CompactTextString(this) }
func (*RpbListKeysReq) ProtoMessage()       {}

func (this *RpbListKeysReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

type RpbListKeysResp struct {
	Keys             [][]byte `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Done             *bool    `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *RpbListKeysResp) Reset()         { *this = RpbListKeysResp{} }
func (this *RpbListKeysResp) String() string { return proto.CompactTextString(this) }
func (*RpbListKeysResp) ProtoMessage()       {}

func (this *RpbListKeysResp) GetDone() bool {
	if this != nil && this.Done != nil {
		return *this.Done
	}
	return false
}

type RpbGetBucketReq struct {
	Bucket           []byte `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbGetBucketReq) Reset()         { *this = RpbGetBucketReq{} }
func (this *RpbGetBucketReq) String() string { return proto.CompactTextString(this) }
func (*RpbGetBucketReq) ProtoMessage()       {}

func (this *RpbGetBucketReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

type RpbGetBucketResp struct {
	Props            *RpbBucketProps `protobuf:"bytes,1,req,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *RpbGetBucketResp) Reset()         { *this = RpbGetBucketResp{} }
func (this *RpbGetBucketResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetBucketResp) ProtoMessage()       {}

func (this *RpbGetBucketResp) GetProps() *RpbBucketProps {
	if this != nil {
		return this.Props
	}
	return nil
}

type RpbSetBucketReq struct {
	Bucket           []byte          `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Props            *RpbBucketProps `protobuf:"bytes,2,req,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *RpbSetBucketReq) Reset()         { *this = RpbSetBucketReq{} }
func (this *RpbSetBucketReq) String() string { return proto.CompactTextString(this) }
func (*RpbSetBucketReq) ProtoMessage()       {}

func (this *RpbSetBucketReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbSetBucketReq) GetProps() *RpbBucketProps {
	if this != nil {
		return this.Props
	}
	return nil
}

type RpbMapRedReq struct {
	Request          []byte `protobuf:"bytes,1,req,name=request" json:"request,omitempty"`
	ContentType      []byte `protobuf:"bytes,2,req,name=content_type" json:"content_type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbMapRedReq) Reset()         { *this = RpbMapRedReq{} }
func (this *RpbMapRedReq) String() string { return proto.CompactTextString(this) }
func (*RpbMapRedReq) ProtoMessage()       {}

func (this *RpbMapRedReq) GetRequest() []byte {
	if this != nil {
		return this.Request
	}
	return nil
}

func (this *RpbMapRedReq) GetContentType() []byte {
	if this != nil {
		return this.ContentType
	}
	return nil
}

type RpbMapRedResp struct {
	Phase            *uint32 `protobuf:"varint,1,opt,name=phase" json:"phase,omitempty"`
	Response         []byte  `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	Done             *bool   `protobuf:"varint,3,opt,name=done" json:"done,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbMapRedResp) Reset()         { *this = RpbMapRedResp{} }
func (this *RpbMapRedResp) String() string { return proto.CompactTextString(this) }
func (*RpbMapRedResp) ProtoMessage()       {}

func (this *RpbMapRedResp) GetPhase() uint32 {
	if this != nil && this.Phase != nil {
		return *this.Phase
	}
	return 0
}

func (this *RpbMapRedResp) GetResponse() []byte {
	if this != nil {
		return this.Response
	}
	return nil
}

func (this *RpbMapRedResp) GetDone() bool {
	if this != nil && this.Done != nil {
		return *this.Done
	}
	return false
}

type RpbIndexReq struct {
	Bucket           []byte                      `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Index            []byte                      `protobuf:"bytes,2,req,name=index" json:"index,omitempty"`
	Qtype            *RpbIndexReq_IndexQueryType `protobuf:"varint,3,req,name=qtype,enum=RpbIndexReq_IndexQueryType" json:"qtype,omitempty"`
	Key              []byte                      `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	RangeMin         []byte                      `protobuf:"bytes,5,opt,name=range_min" json:"range_min,omitempty"`
	RangeMax         []byte                      `protobuf:"bytes,6,opt,name=range_max" json:"range_max,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (this *RpbIndexReq) Reset()         { *this = RpbIndexReq{} }
func (this *RpbIndexReq) String() string { return proto.CompactTextString(this) }
func (*RpbIndexReq) ProtoMessage()       {}

func (this *RpbIndexReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbIndexReq) GetIndex() []byte {
	if this != nil {
		return this.Index
	}
	return nil
}

func (this *RpbIndexReq) GetQtype() RpbIndexReq_IndexQueryType {
	if this != nil && this.Qtype != nil {
		return *this.Qtype
	}
	return 0
}

func (this *RpbIndexReq) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbIndexReq) GetRangeMin() []byte {
	if this != nil {
		return this.RangeMin
	}
	return nil
}

func (this *RpbIndexReq) GetRangeMax() []byte {
	if this != nil {
		return this.RangeMax
	}
	return nil
}

type RpbIndexResp struct {
	Keys             [][]byte `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *RpbIndexResp) Reset()         { *this = RpbIndexResp{} }
func (this *RpbIndexResp) String() string { return proto.CompactTextString(this) }
func (*RpbIndexResp) ProtoMessage()       {}

type RpbContent struct {
	Value            []byte     `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	ContentType      []byte     `protobuf:"bytes,2,opt,name=content_type" json:"content_type,omitempty"`
	Charset          []byte     `protobuf:"bytes,3,opt,name=charset" json:"charset,omitempty"`
	ContentEncoding  []byte     `protobuf:"bytes,4,opt,name=content_encoding" json:"content_encoding,omitempty"`
	Vtag             []byte     `protobuf:"bytes,5,opt,name=vtag" json:"vtag,omitempty"`
	Links            []*RpbLink `protobuf:"bytes,6,rep,name=links" json:"links,omitempty"`
	LastMod          *uint32    `protobuf:"varint,7,opt,name=last_mod" json:"last_mod,omitempty"`
	LastModUsecs     *uint32    `protobuf:"varint,8,opt,name=last_mod_usecs" json:"last_mod_usecs,omitempty"`
	Usermeta         []*RpbPair `protobuf:"bytes,9,rep,name=usermeta" json:"usermeta,omitempty"`
	Indexes          []*RpbPair `protobuf:"bytes,10,rep,name=indexes" json:"indexes,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *RpbContent) Reset()         { *this = RpbContent{} }
func (this *RpbContent) String() string { return proto.CompactTextString(this) }
func (*RpbContent) ProtoMessage()       {}

func (this *RpbContent) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

func (this *RpbContent) GetContentType() []byte {
	if this != nil {
		return this.ContentType
	}
	return nil
}

func (this *RpbContent) GetCharset() []byte {
	if this != nil {
		return this.Charset
	}
	return nil
}

func (this *RpbContent) GetContentEncoding() []byte {
	if this != nil {
		return this.ContentEncoding
	}
	return nil
}

func (this *RpbContent) GetVtag() []byte {
	if this != nil {
		return this.Vtag
	}
	return nil
}

func (this *RpbContent) GetLastMod() uint32 {
	if this != nil && this.LastMod != nil {
		return *this.LastMod
	}
	return 0
}

func (this *RpbContent) GetLastModUsecs() uint32 {
	if this != nil && this.LastModUsecs != nil {
		return *this.LastModUsecs
	}
	return 0
}

type RpbLink struct {
	Bucket           []byte `protobuf:"bytes,1,opt,name=bucket" json:"bucket,omitempty"`
	Key              []byte `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Tag              []byte `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbLink) Reset()         { *this = RpbLink{} }
func (this *RpbLink) String() string { return proto.CompactTextString(this) }
func (*RpbLink) ProtoMessage()       {}

func (this *RpbLink) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbLink) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbLink) GetTag() []byte {
	if this != nil {
		return this.Tag
	}
	return nil
}

type RpbBucketProps struct {
	NVal             *uint32 `protobuf:"varint,1,opt,name=n_val" json:"n_val,omitempty"`
	AllowMult        *bool   `protobuf:"varint,2,opt,name=allow_mult" json:"allow_mult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbBucketProps) Reset()         { *this = RpbBucketProps{} }
func (this *RpbBucketProps) String() string { return proto.CompactTextString(this) }
func (*RpbBucketProps) ProtoMessage()       {}

func (this *RpbBucketProps) GetNVal() uint32 {
	if this != nil && this.NVal != nil {
		return *this.NVal
	}
	return 0
}

func (this *RpbBucketProps) GetAllowMult() bool {
	if this != nil && this.AllowMult != nil {
		return *this.AllowMult
	}
	return false
}

func init() {
	proto.RegisterEnum("RpbIndexReq_IndexQueryType", RpbIndexReq_IndexQueryType_name, RpbIndexReq_IndexQueryType_value)
}
